/*
  文件：utils/mock_data.dart
  说明：
  - 提供应用演示/开发所需的静态 Mock 数据：
    1) dailyChallenge：每日挑战
    2) initialPet：默认宠物档案（作为示例/未登录占位）
    3) otherPets：其他宠物列表（用于探索/推荐）
    4) posts：动态列表（Feed）
  注意：本文件仅添加中文注释，不改变数据结构与逻辑。
*/
import '../models/types.dart';

/// Mock 数据提供者：集中管理应用示例数据
class MockData {
  /// Mock 用户 ID（用于开发阶段）
  /// 在真实 Firebase 环境中，这个值会从 AuthProvider 获取
  static const String mockUserId = 'mock_user_12345';

  /// 每日挑战：用于首页 ChallengeCard 展示
  static final Challenge dailyChallenge = Challenge(
    id: 'c1',
    title: 'The "Boop" Shot',
    description: 'Take a close-up photo of your pet\'s nose!',
    reward: 50,
    icon: '🐽',
    color: 'pink',
    completed: false,
  );

  /// 默认宠物：作为当前用户未登录/初始宠物的占位
  static final Pet initialPet = Pet(
    id: 'p1',
    name: 'Barnaby',
    type: PetType.DOG,
    breed: 'Golden Retriever',
    birthDate: '2021-05-10',
    avatarUrl: 'https://picsum.photos/id/1025/200/200',
    bio: 'Sock thief & Professional napper. 🧦💤',
    vaccines: [
      Vaccine(id: 'v1', name: 'Rabies', dateAdministered: '2023-05-10', dueDate: '2024-05-10', veterinarian: 'Dr. Smith'),
      Vaccine(id: 'v2', name: 'DHPP', dateAdministered: '2023-02-15', dueDate: '2024-02-15', veterinarian: 'Dr. Smith'),
    ],
    weightHistory: [
      WeightRecord(id: 'weight_1', date: 'Oct', weight: 29.0),
      WeightRecord(id: 'weight_2', date: 'Nov', weight: 29.2),
      WeightRecord(id: 'weight_3', date: 'Dec', weight: 30.1),
      WeightRecord(id: 'weight_4', date: 'Jan', weight: 29.8),
    ],
    gallery: [
      'https://picsum.photos/id/237/300/300',
      'https://picsum.photos/id/1025/300/300',
      'https://picsum.photos/id/169/300/300',
      'https://picsum.photos/id/659/300/300',
      'https://picsum.photos/id/582/300/300',
      'https://picsum.photos/id/40/300/300',
    ],
    userId: mockUserId,
  );

  /// 其他宠物：探索页的推荐数据
  static final List<Pet> otherPets = [
    Pet(
      id: 'p2',
      name: 'Luna',
      type: PetType.DOG,
      breed: 'Husky',
      birthDate: '2022-01-15',
      avatarUrl: 'https://picsum.photos/id/237/200/200',
      bio: 'I sing the song of my people at 3AM. 🐺',
      vaccines: [],
      weightHistory: [],
      gallery: ['https://picsum.photos/id/1062/300/300', 'https://picsum.photos/id/1074/300/300'],
      isFollowing: false,
      userId: 'mock_user_other_1',
    ),
    Pet(
      id: 'p3',
      name: 'Mochi',
      type: PetType.CAT,
      breed: 'Scottish Fold',
      birthDate: '2020-08-20',
      avatarUrl: 'https://picsum.photos/id/40/200/200',
      bio: 'Judging you silently.',
      vaccines: [],
      weightHistory: [],
      gallery: ['https://picsum.photos/id/219/300/300'],
      isFollowing: true,
      userId: 'mock_user_other_2',
    ),
    Pet(
      id: 'p4',
      name: 'Charlie',
      type: PetType.DOG,
      breed: 'Corgi',
      birthDate: '2023-01-01',
      avatarUrl: 'https://picsum.photos/id/200/200/200',
      bio: 'Short legs, big dreams.',
      vaccines: [],
      weightHistory: [],
      gallery: [],
      isFollowing: false,
      userId: 'mock_user_other_3',
    ),
  ];

  /// 动态列表：用于 FeedCard 的展示数据
  static final List<Post> posts = [
    Post(
      id: 'post1',
      authorId: 'p2',
      authorName: 'Luna the Husky',
      authorAvatar: 'https://picsum.photos/id/237/100/100',
      content: 'Just sang the song of my people at 3AM. Humans loved it. 🎤',
      imageUrl: 'https://picsum.photos/id/1062/600/600',
      likes: 124,
      comments: 12,
      timestamp: '2h ago',
      date: '2023-10-25',
      location: 'Central Park',
      mood: 'Dramatic',
      category: PostCategory.snapshot,
      userId: 'mock_user_other_1',
    ),
    Post(
      id: 'post2',
      authorId: 'p3',
      authorName: 'Mochi the Cat',
      authorAvatar: 'https://picsum.photos/id/40/100/100',
      content: 'The box was better than the toy inside.',
      imageUrl: 'https://picsum.photos/id/219/600/600',
      likes: 89,
      comments: 5,
      timestamp: '5h ago',
      date: '2023-10-24',
      mood: 'Judgy',
      category: PostCategory.play,
      userId: 'mock_user_other_2',
    ),
    Post(
      id: 'post3',
      authorId: 'p4',
      authorName: 'Charlie',
      authorAvatar: 'https://picsum.photos/id/200/100/100',
      content: 'Nap time after a long walk.',
      imageUrl: 'https://picsum.photos/id/200/600/600',
      likes: 200,
      comments: 20,
      timestamp: '1h ago',
      date: '2023-10-26',
      mood: 'Sleepy',
      category: PostCategory.sleepy,
      userId: 'mock_user_other_3',
    ),
    Post(
      id: 'post4',
      authorId: 'p1',
      authorName: 'Barnaby',
      authorAvatar: 'https://picsum.photos/id/1025/100/100',
      content: 'Squirrel patrol is SERIOUS business! Caught three trying to invade MY yard. They won\'t be back! 🐿️',
      imageUrl: 'https://picsum.photos/id/1025/600/600',
      likes: 156,
      comments: 8,
      timestamp: '3h ago',
      date: '2023-10-25',
      location: 'Backyard HQ',
      mood: 'Protective',
      category: PostCategory.play,
      userId: mockUserId,
    ),
    Post(
      id: 'post5',
      authorId: 'p2',
      authorName: 'Luna the Husky',
      authorAvatar: 'https://picsum.photos/id/237/100/100',
      content: 'Morning walkies hit different when there\'s snow on the ground! ❄️ This is what I was BORN for!',
      imageUrl: 'https://picsum.photos/id/1074/600/600',
      likes: 312,
      comments: 24,
      timestamp: '6h ago',
      date: '2023-10-24',
      location: 'Snowy Trail',
      mood: 'Excited',
      category: PostCategory.walk,
      userId: 'mock_user_other_1',
    ),
    Post(
      id: 'post6',
      authorId: 'p4',
      authorName: 'Charlie',
      authorAvatar: 'https://picsum.photos/id/200/100/100',
      content: 'When you\'re 90% ears and 10% dog 👂 Mom says I\'m "all personality" which is code for "chaos goblin"',
      imageUrl: 'https://picsum.photos/id/169/600/600',
      likes: 278,
      comments: 31,
      timestamp: '8h ago',
      date: '2023-10-24',
      mood: 'Sassy',
      category: PostCategory.snapshot,
      userId: 'mock_user_other_3',
    ),
    Post(
      id: 'post7',
      authorId: 'p3',
      authorName: 'Mochi the Cat',
      authorAvatar: 'https://picsum.photos/id/40/100/100',
      content: 'Found the perfect sunbeam. Do NOT disturb for the next 4 hours. ☀️😴',
      imageUrl: 'https://picsum.photos/id/1084/600/600',
      likes: 145,
      comments: 3,
      timestamp: '10h ago',
      date: '2023-10-23',
      mood: 'Blissful',
      category: PostCategory.sleepy,
      userId: 'mock_user_other_2',
    ),
    Post(
      id: 'post8',
      authorId: 'p1',
      authorName: 'Barnaby',
      authorAvatar: 'https://picsum.photos/id/1025/100/100',
      content: 'Stolen another sock. That\'s 47 this month. They\'ll never find my secret stash. 🧦',
      likes: 203,
      comments: 15,
      timestamp: '12h ago',
      date: '2023-10-23',
      location: 'Laundry Room',
      mood: 'Mischievous',
      category: PostCategory.play,
      userId: mockUserId,
    ),
    Post(
      id: 'post9',
      authorId: 'p5',
      authorName: 'Pawsome Treats Co.',
      authorAvatar: 'https://picsum.photos/id/1003/100/100',
      content: '🎉 NEW! Peanut Butter Bliss Treats - Made with 100% natural ingredients your pup will go CRAZY for! Limited time: 20% off with code WOOF20',
      imageUrl: 'https://picsum.photos/id/1003/600/600',
      likes: 67,
      comments: 4,
      timestamp: '1d ago',
      date: '2023-10-22',
      isAd: true,
      category: PostCategory.snapshot,
      userId: 'mock_advertiser_1',
    ),
    Post(
      id: 'post10',
      authorId: 'p2',
      authorName: 'Luna the Husky',
      authorAvatar: 'https://picsum.photos/id/237/100/100',
      content: 'Post-walk nap hits different when you\'ve chased every leaf in the park 🍂💤',
      imageUrl: 'https://picsum.photos/id/433/600/600',
      likes: 189,
      comments: 9,
      timestamp: '1d ago',
      date: '2023-10-22',
      location: 'Couch Kingdom',
      mood: 'Exhausted',
      category: PostCategory.sleepy,
      userId: 'mock_user_other_1',
    ),
  ];

  /// Mock moments（照片/视频时刻）：用于 Moments 标签页
  static final List<Moment> moments = [
    Moment(
      id: 'm1',
      mediaUrl: 'https://picsum.photos/id/1025/400/400',
      date: '2023-11-15',
      isVideo: false,
    ),
    Moment(
      id: 'm2',
      mediaUrl: 'https://picsum.photos/id/237/400/400',
      date: '2023-11-10',
      isVideo: false,
    ),
    Moment(
      id: 'm3',
      mediaUrl: 'https://picsum.photos/id/169/400/400',
      date: '2023-11-05',
      isVideo: false,
    ),
    Moment(
      id: 'm4',
      mediaUrl: 'https://picsum.photos/id/659/400/400',
      date: '2023-10-28',
      isVideo: false,
    ),
    Moment(
      id: 'm5',
      mediaUrl: 'https://picsum.photos/id/582/400/400',
      date: '2023-10-20',
      isVideo: false,
    ),
    Moment(
      id: 'm6',
      mediaUrl: 'https://picsum.photos/id/1074/400/400',
      date: '2023-10-15',
      isVideo: false,
    ),
    Moment(
      id: 'm7',
      mediaUrl: 'https://picsum.photos/id/433/400/400',
      date: '2023-10-08',
      isVideo: false,
    ),
    Moment(
      id: 'm8',
      mediaUrl: 'https://picsum.photos/id/1062/400/400',
      date: '2023-10-01',
      isVideo: false,
    ),
    Moment(
      id: 'm9',
      mediaUrl: 'https://picsum.photos/id/180/400/400',
      date: '2023-09-25',
      isVideo: true,
    ),
    Moment(
      id: 'm10',
      mediaUrl: 'https://picsum.photos/id/367/400/400',
      date: '2023-09-18',
      isVideo: false,
    ),
    Moment(
      id: 'm11',
      mediaUrl: 'https://picsum.photos/id/452/400/400',
      date: '2023-09-10',
      isVideo: false,
    ),
    Moment(
      id: 'm12',
      mediaUrl: 'https://picsum.photos/id/225/400/400',
      date: '2023-09-05',
      isVideo: false,
    ),
  ];
}