// Mocks generated by Mockito 5.4.4 from annotations
// in ollie_paw/test/providers/currency_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ollie_paw/models/types.dart' as _i4;
import 'package:ollie_paw/services/persistence_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistenceService extends _i1.Mock
    implements _i2.PersistenceService {
  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> savePet(_i4.Pet? pet) => (super.noSuchMethod(
        Invocation.method(
          #savePet,
          [pet],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i4.Pet? getPet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPet,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.Pet?);

  @override
  List<_i4.Pet> getAllPets() => (super.noSuchMethod(
        Invocation.method(
          #getAllPets,
          [],
        ),
        returnValue: <_i4.Pet>[],
        returnValueForMissingStub: <_i4.Pet>[],
      ) as List<_i4.Pet>);

  @override
  _i3.Future<bool> deletePet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePet,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> saveCurrentPetId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentPetId,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> saveUser(_i4.UserProfile? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i4.UserProfile? getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.UserProfile?);

  @override
  _i3.Future<bool> saveCurrentUserId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentUserId,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> saveTreats(int? treats) => (super.noSuchMethod(
        Invocation.method(
          #saveTreats,
          [treats],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  int getTreats() => (super.noSuchMethod(
        Invocation.method(
          #getTreats,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<bool> saveLastCheckIn(String? date) => (super.noSuchMethod(
        Invocation.method(
          #saveLastCheckIn,
          [date],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> saveConsecutiveDays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #saveConsecutiveDays,
          [days],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  int getConsecutiveDays() => (super.noSuchMethod(
        Invocation.method(
          #getConsecutiveDays,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Future<bool> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
